#!/bin/sh

############################################################################################################
# Run unit tests
############################################################################################################
# run all tests inside the test directory
./node_modules/.bin/mocha ./test/*.js

############################################################################################################
# Validate app directory structure
############################################################################################################
# Determine if a 'test' directory exists in the root directory
if [ -d ./test ]; then
    echo "'test' directory exists"
else
    echo "'test' directory doesn't exist"
fi

# Determine if a 'dist' directory exists in the root directory
if [ -d ./dist ]; then
    echo "'dist' directory exists"
else
    echo "'dist' directory doesn't exist"
fi

# Determine if a 'src' directory exists in the root directory
if [ -d ./src ]; then
    echo "'src' directory exists"
else
    echo "'src' directory doesn't exist"
fi
