#!/bin/sh

############################################################################################################
# Run unit tests
############################################################################################################
# run all tests inside the test directory
./node_modules/.bin/mocha ./test/*.js

############################################################################################################
# Validate app directory structure
############################################################################################################
# Determine if a 'test' directory exists in the root directory
if [ -d ./test ]; then
    echo "'test' directory exists"
else
    echo "'test' directory doesn't exist"
fi

# Determine if a 'dist' directory exists in the root directory
if [ -d ./dist ]; then
    echo "'dist' directory exists"
    # Determine if a 'dist/server' directory exists in the root directory
    if [ -d ./dist/server ]; then
        echo "'dist/server' directory exists"
    else
        echo "'dist/server' directory doesn't exist"
    fi
    # Determine if a 'dist/client' directory exists in the root directory
    if [ -d ./dist/client ]; then
        echo "'dist/client' directory exists"
    else
        echo "'dist/client' directory doesn't exist"
    fi
else
    echo "'dist' directory doesn't exist"
fi

# Determine if a 'src' directory exists in the root directory
if [ -d ./src ]; then
    echo "'src' directory exists"
else
    echo "'src' directory doesn't exist"
fi
